### ISSUE TITLE
Two prompt-toolkit packages on conda-forge

### ISSUE THREAD

**Issue by bsipocz** [conda-forge/prompt_toolkit-feedstock#46]
I have received a user report that two of the `prompt-toolkit` packages are pulled to be installed when they try to install astroquery. I've only found this feedstock, and now the situation is very confusing:

```
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    astroquery-0.4.1           |     pyh9f0ad1d_0         3.0 MB  conda-forge
    backcall-0.2.0             |     pyh9f0ad1d_0          13 KB  conda-forge
    prompt-toolkit-3.0.5       |             py_1         233 KB  conda-forge
    prompt_toolkit-3.0.5       |                1           4 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         3.2 MB
```

Could you please advise what's the situation, which one is to be used and where the other one is coming from? (Neither of them are direct dependencies of astroquery, so I'm in the dark why these are even necessary to be installed).

cc @conda-forge-admin

**Comment by jakirkham** [comment]
One or both is fine. One of them is a metapackage added to make life easier for downstream users. The metapackage was added in PR ( https://github.com/conda-forge/prompt_toolkit-feedstock/pull/40 ). Both are probably gotten because [`ipython` requires it]( https://github.com/conda-forge/ipython-feedstock/blob/1b03939cc9f499ae95f4b63d119d6c69d379128c/recipe/meta.yaml#L33 ).

We made some fixes the other day to resolve some user reported issues ( https://github.com/conda-forge/prompt_toolkit-feedstock/issues/44 ) ( https://github.com/conda-forge/ipython-feedstock/pull/106 ), which is probably why this is only now showing up.

(side note: `@conda-forge-admin` is a bot)

cc @ocefpaf

**Comment by scopatz** [comment]
If you don't want both, just rely on `prompt-toolkit`

**Comment by ocefpaf** [comment]
Pretty much what @jakirkham said above. If you specify the underscore version, which is the metapackage, you'll get the hyphen version, that is is real package. There is nothing wrong in having both. That exists to make the life of those expecting the same experience as pip a little bit easier.

**Comment by bsipocz** [comment]
Thank you all, it all makes sense now. I'm sorry for the noise.
